env_variables:
    APP_SECRET:    "whitershadeofpale"
    DATABASE_URL:  "postgresql://pairing:pairing@localhost:5432/oss"
    PORT:          5001
    FLASK_ENV:     development
    PYTHONUNBUFFERED: 1